---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  tags: update

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  tags: install

- name: Start and enable Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  tags: service
